import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { gsap } from 'gsap';
import './MessageBoard.css';
import envelopeArt from '../../../design-assets/page5/古画荔枝信封_透明背景.webp';
import envelopeBackArt from '../../../design-assets/page5/古画荔枝信封背面_透明背景.webp';
import envelopeOpenArt from '../../../design-assets/page5/古画荔枝信封背面_打开_透明背景.webp';
import unfoldedPaperArt from '../../../design-assets/page5/古画荔枝信纸_完全展开_透明背景.webp';
import titleSeal from '../../../design-assets/home/home-bg-yin.webp';
import SplashCursor from './SplashCursor.jsx';
import {createMessage,fetchMessages} from '../../lib/messageRepository';

type BoardState='idle'|'composing'|'folding'|'sealing'|'flying'|'floating'|'opening'|'revealing'|'displayed'|'closing';
type Message={id:string;content:string;author:string;createdAt:string;position:{x:number;y:number};rotation:number;scale:number;status:'floating'};
export const MESSAGE_API={list:{method:'GET',url:'/api/messages'},create:{method:'POST',url:'/api/messages'}} as const;
const STORAGE='yunxiu-song-message-board-v1';
const MOTION={compose:.45,fold:.5,seal:.38,flight:1.05,open:.78,reveal:.85,close:.7,ease:'power2.inOut'};
const seeds=['见字如晤。愿你行过山长水阔，仍有清风明月相伴。','偶然到访，留一笔墨痕。愿你的故事常写常新。','今日窗外细雨，读到这里，忽觉人间可爱。','山水有相逢，来日皆可期。','愿所行皆坦途，所念皆如愿。','借一页宣纸，寄一声遥远的问候。'];
const slots=[{x:11,y:21},{x:25,y:8},{x:40,y:25},{x:57,y:11},{x:72,y:27},{x:86,y:9},{x:48,y:4},{x:66,y:3}];
const arrangeMessages=(items:Message[])=>items.slice(0,6).map((message,index)=>({...message,position:{...slots[index]},rotation:(index%2?-1:1)*(1.4+(index%3)*.8),scale:.88+(index%4)*.045}));
const randomSample=(items:Message[],count=6)=>{const pool=[...items];for(let i=pool.length-1;i>0;i-=1){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}return pool.slice(0,count)};
const seedNames=['远山客','临水人','听雨','南枝','无名书友','归舟'];
const makeSeed=(content:string,i:number):Message=>({id:`seed-${i}`,content,author:seedNames[i%seedNames.length],createdAt:'旧日留书',position:slots[i%slots.length],rotation:(i%2?-1:1)*(1.4+(i%3)*.8),scale:.88+(i%4)*.045,status:'floating'});
function loadOwnMessages(){if(typeof window==='undefined')return[];try{const saved=JSON.parse(localStorage.getItem(STORAGE)||'[]');return Array.isArray(saved)?saved.filter((message:Message)=>message?.id?.startsWith('msg-')).slice(0,12):[]}catch{return[]}}
function mergeMessages(remote:Message[]=[]){const unique=new Map<string,Message>();[...loadOwnMessages(),...remote,...seeds.map(makeSeed)].forEach(message=>{if(message?.id&&!unique.has(message.id))unique.set(message.id,message)});return arrangeMessages([...unique.values()])}
function saveOwn(messages:Message[]){localStorage.setItem(STORAGE,JSON.stringify(messages.filter(m=>m.id.startsWith('msg-')).slice(0,12)))}

export default function MessageBoard(){
 const [messages,setMessages]=useState<Message[]>(()=>mergeMessages()),[value,setValue]=useState(''),[author,setAuthor]=useState(''),[phase,setPhase]=useState<BoardState>('idle'),[active,setActive]=useState<string|null>(null),[sent,setSent]=useState(false),[refreshing,setRefreshing]=useState(false),[switching,setSwitching]=useState(false);
 const stage=useRef<HTMLDivElement>(null),composer=useRef<HTMLDivElement>(null),outgoing=useRef<HTMLDivElement>(null),reader=useRef<HTMLDivElement>(null),paper=useRef<HTMLDivElement>(null),chars=useRef<HTMLSpanElement[]>([]),tl=useRef<gsap.core.Timeline|null>(null);
 useEffect(()=>{gsap.globalTimeline.timeScale(.8);return()=>{gsap.globalTimeline.timeScale(1)}},[]);
 useLayoutEffect(()=>{if(phase==='composing'&&outgoing.current)gsap.set(outgoing.current,{xPercent:0,y:0})},[phase]);
 useEffect(()=>{let alive=true;fetchMessages(6).then(remote=>{if(alive)setMessages(mergeMessages((remote??[]) as Message[]))});return()=>{alive=false}},[]);
 const selected=useMemo(()=>messages.find(m=>m.id===active),[messages,active]);
 useEffect(()=>{if(messages.length)saveOwn(messages)},[messages]);
 const refreshMessages=useCallback(async()=>{if(refreshing||phase!=='idle')return;setRefreshing(true);const remote=await fetchMessages(100);if(!remote||remote.length<6){setRefreshing(false);return}const next=arrangeMessages(randomSample(remote,6));const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;setSwitching(true);if(!reduced)await new Promise(resolve=>window.setTimeout(resolve,320));setMessages(next);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));setSwitching(false);setRefreshing(false)},[phase,refreshing]);
 const close=useCallback((done?:()=>void)=>{if(!active||phase==='closing')return done?.();setPhase('closing');tl.current?.kill();const t=gsap.timeline({onComplete:()=>{setActive(null);setPhase('idle');done?.()}});tl.current=t;t.to(chars.current,{y:16,opacity:0,stagger:{each:.009,from:'end'},duration:.2}).set('.opened-envelope .envelope-open-frame',{opacity:1}).set('.opened-envelope .envelope-closed-frame',{opacity:0}).set('.opened-envelope .envelope-visual',{opacity:0}).to(paper.current,{opacity:0,duration:.32,ease:MOTION.ease},'<.03').to('.opened-envelope .envelope-visual',{opacity:1,duration:.24,ease:'power1.out'},'<.1').to('.opened-envelope .envelope-open-frame',{opacity:0,duration:.42,ease:MOTION.ease},'<.12').to('.opened-envelope .envelope-closed-frame',{opacity:1,duration:.42,ease:MOTION.ease},'<').to(reader.current,{scale:.72,opacity:0,duration:MOTION.close,ease:MOTION.ease},'<.14').to('.floating-envelope',{opacity:.9,duration:.32},'<.25');t.timeScale(.8);if(matchMedia('(prefers-reduced-motion: reduce)').matches)t.timeScale(100)},[active,phase]);
 const open=useCallback((id:string)=>{const run=()=>{setActive(id);setPhase('opening')};if(active&&active!==id)close(run);else if(!active)run()},[active,close]);
 useLayoutEffect(()=>{if(!selected)return;chars.current=[];gsap.set(reader.current,{opacity:0,scale:.68,y:20});gsap.set(paper.current,{opacity:0});gsap.set('.opened-envelope .envelope-visual',{opacity:1});gsap.set('.opened-envelope .envelope-closed-frame',{opacity:1});gsap.set('.opened-envelope .envelope-open-frame',{opacity:0});const t=gsap.timeline({onComplete:()=>setPhase('displayed')});tl.current=t;t.to('.floating-envelope',{opacity:.24,duration:.35}).to(reader.current,{opacity:1,scale:1,y:0,duration:MOTION.open,ease:MOTION.ease},0).to('.opened-envelope .envelope-closed-frame',{opacity:0,duration:.48,ease:MOTION.ease},.3).to('.opened-envelope .envelope-open-frame',{opacity:1,duration:.48,ease:MOTION.ease},'<').call(()=>setPhase('revealing')).to('.opened-envelope .envelope-visual',{opacity:0,duration:.42,ease:'power1.inOut'}).to(paper.current,{opacity:1,duration:.58,ease:'power2.out'},'<.08').fromTo(chars.current,{opacity:0,x:()=>gsap.utils.random(-65,65),y:()=>gsap.utils.random(18,75),rotation:()=>gsap.utils.random(-12,12),filter:'blur(4px)'},{opacity:1,x:0,y:0,rotation:0,filter:'blur(0px)',duration:MOTION.reveal,stagger:.018,ease:'power2.out'},'<.12');t.timeScale(.8);if(matchMedia('(prefers-reduced-motion: reduce)').matches)t.timeScale(100);return()=>{t.kill()}},[selected]);
 const submit=()=>{const content=value.trim(),signature=author.trim();if(!content||!signature||phase!=='idle')return;setSent(false);setPhase('composing');tl.current?.kill();gsap.set(outgoing.current,{display:'grid',opacity:0,xPercent:0,x:0,y:0,scale:1,rotation:0});gsap.set('.outgoing-paper-visual',{opacity:1,scale:1});gsap.set('.outgoing-envelope-visual',{opacity:0});gsap.set('.outgoing-letter .envelope-open-frame',{opacity:1});gsap.set('.outgoing-letter .envelope-closed-frame',{opacity:0});const id=`msg-${Date.now()}`,targetIndex=0,slot=slots[targetIndex];const msg:Message={id,content,author:signature,createdAt:new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date()),position:slot,rotation:-2.1,scale:.94,status:'floating'};saveOwn([msg,...loadOwnMessages()]);void createMessage(msg);const targetX=()=>innerWidth*(slot.x/100)-innerWidth/2,targetY=()=>-innerHeight*.48+slot.y*1.25;const t=gsap.timeline({onComplete:()=>{gsap.set(composer.current,{opacity:0});setMessages(current=>arrangeMessages([msg,...current.filter(message=>message.id!==msg.id)]));setValue('');setAuthor('');setPhase('idle');setSent(true);gsap.set(outgoing.current,{display:'none'});gsap.to(composer.current,{opacity:1,duration:.62,delay:.06,ease:'power1.inOut'})}});tl.current=t;t.to(composer.current,{opacity:.24,duration:MOTION.compose,ease:'power1.inOut'}).fromTo(outgoing.current,{opacity:0,y:0},{opacity:1,y:0,duration:MOTION.compose,ease:'power2.out'},0).fromTo('.outgoing-sheet',{opacity:0,y:18},{opacity:1,y:0,duration:.42,ease:'power2.out'},.12).call(()=>setPhase('folding')).to('.outgoing-paper-visual',{opacity:0,scale:.96,duration:.58,ease:'power1.inOut'}).to('.outgoing-envelope-visual',{opacity:1,duration:.42},'<.14').call(()=>setPhase('sealing')).to(composer.current,{opacity:0,duration:.42,ease:'power1.inOut'},'<').to('.outgoing-letter .envelope-open-frame',{opacity:0,duration:.52,ease:MOTION.ease},'<.08').to('.outgoing-letter .envelope-closed-frame',{opacity:1,duration:.52,ease:MOTION.ease},'<').to('.outgoing-seal',{opacity:1,scale:1,duration:.26,ease:'power2.out'}).call(()=>setPhase('flying')).to('.floating-envelope:last-child',{opacity:0,translateY:-8,duration:.9,ease:'power1.inOut'},'<').to(outgoing.current,{keyframes:[{x:()=>targetX()*.18,y:()=>-innerHeight*.13,scale:.94,rotation:-3,opacity:.92},{x:()=>targetX()*.62,y:()=>targetY()*.46-innerHeight*.08,scale:.76,rotation:4,opacity:.62},{x:targetX,y:targetY,scale:msg.scale*.58,rotation:msg.rotation,opacity:.08}],duration:1.9,ease:'power1.inOut'},'<.18');if(matchMedia('(prefers-reduced-motion: reduce)').matches)t.timeScale(100)};
 return <div className="message-board" ref={stage} onPointerDown={e=>{if(e.target===stage.current&&active)close()}}><SplashCursor RAINBOW_MODE={false} COLOR="#fff8df" SECONDARY_COLOR="#ffffff" COLOR_INTENSITY={.24} SPLAT_RADIUS={.32} DENSITY_DISSIPATION={1.8} VELOCITY_DISSIPATION={1.2} Z_INDEX={0}/>
  <section className={`letter-sky${switching?' is-switching':''}`} aria-label="漂浮的留言信封" aria-busy={refreshing}>{messages.map((m,i)=><button key={m.id} className={`floating-envelope envelope-${i} ${m.id.startsWith('msg-')?'is-user-message':''}`} style={{'--x':`${m.position.x}%`,'--y':`${m.position.y}%`,'--r':`${m.rotation}deg`,'--s':m.scale,'--d':`${6.8+i*.55}s`} as React.CSSProperties} onClick={()=>open(m.id)} aria-label={`打开${m.author||'无名书友'}的留言`}><img src={envelopeArt.src} alt=""/><b>{m.author||'无名书友'}</b></button>)}</section>
  <button className="message-refresh" type="button" onClick={refreshMessages} disabled={refreshing||phase!=='idle'} aria-label={refreshing?'正在从数据库换取六封信件':'从数据库随机换取六封信件'}><span>{refreshing?'换信中':'换一换'}</span></button>
  <header className="board-title"><p>Letters in the Wind</p><span className="board-title-line"><h1>云中寄书</h1><img className="board-title-seal" src={titleSeal.src} alt="云岫印"/></span><span className="board-subtitle" aria-label="片纸无声，亦可抵达">{[...'片纸无声，亦可抵达'].map((char,i)=><i key={i} aria-hidden="true" style={{'--i':i,'--drop-x':`${(i%3-1)*7}px`,'--drop-rotate':`${i%2===0?-7:7}deg`} as React.CSSProperties}>{char}</i>)}</span></header>
    <section className="composer" ref={composer}><label htmlFor="message-content">写一封短笺</label><textarea id="message-content" maxLength={200} value={value} onChange={e=>setValue(e.target.value)} placeholder="见字如晤……" disabled={phase!=='idle'}/><div className="composer-foot"><label className="signature"><span>落款</span><input maxLength={12} value={author} onChange={e=>setAuthor(e.target.value)} placeholder="姓名 / 昵称" disabled={phase!=='idle'}/></label><small>{value.length} / 200</small><button onClick={submit} disabled={!value.trim()||!author.trim()||phase!=='idle'}>留书</button></div></section>
  <div className="outgoing-layer" aria-hidden="true"><div className="outgoing-letter shared-envelope-stage" ref={outgoing}><div className="outgoing-paper-visual"><img src={unfoldedPaperArt.src} alt=""/><div className="outgoing-sheet">{value}</div><em>{author}</em></div><div className="outgoing-envelope-visual"><img className="envelope-closed-frame" src={envelopeBackArt.src} alt=""/><img className="envelope-open-frame" src={envelopeOpenArt.src} alt=""/><b>{author}</b><i className="outgoing-seal"/></div></div></div>
  {selected&&<div className="reading-layer" role="dialog" aria-modal="true" aria-label="留言内容" onPointerDown={e=>{if(e.target===e.currentTarget)close()}}><div className="opened-envelope shared-envelope-stage" ref={reader}><div className="envelope-visual"><img className="envelope-closed-frame" src={envelopeBackArt.src} alt=""/><img className="envelope-open-frame" src={envelopeOpenArt.src} alt=""/></div></div><div className="letter-paper reading-paper" ref={paper}><img src={unfoldedPaperArt.src} alt=""/><button className="reading-close" onClick={()=>close()} aria-label="收起信件">收</button><p>{[...selected.content].map((c,i)=><span key={i} ref={el=>{if(el)chars.current[i]=el}}>{c}</span>)}</p><time>{selected.author||'无名书友'} · {selected.createdAt}</time></div></div>}
 </div>
}
